function [y]=dudt(u,p) %%#ok

data_track_identity=true;

c_d=u(1,:);
c_de=u(2,:);
c_ded=u(3,:);
c_e=u(4,:);

%% p(1) = D_max/D_0    p(2)= E_max/E_0
D_0=319.17;
E_0=819.01;
c_D=p(1) - ([1,1,2,0]*u)./(p(3)*D_0); %%EFFECTIVE C_D.
c_E=p(2) - ([0,1,1,1]*u)./(p(3)*E_0); %%EFFECTIVE C_D.



%LoadInParameters
 d_max=5346.6;  %%Will's canonical value.
%What happens when I mess with this one?
%d_max=535.3;

d_b= 0;
d_p= 67.929; %Or is it 67.929?? Why does this have a value?
d_s=184.66;
e_p=2.0407;
n_s=1;%%Will's values

%n_s=2;

 w__D_to_d= 0; %10^-4 *c_D/c_DScale;
 w__D_to_d__by_d= 0.38336*c_D;   %Note, pretty similar here, almost as if we get one dose of catalysis per avaliable MinD monomer.
 w__D_to_d__by_de= 0.19539*c_D;    %Is half size.
 w__D_to_d__by_ded=0.39594*c_D;     %Is back to full size.
    
 w__E_d_to_de= 0.0033428*c_E;
 w__E_d_to_de__by_de= 1.9885E-10*c_E;
 w__E_d_to_de__by_ded= 1.2952E-9*c_E;
 w__E_d_to_de__by_e= 1.9835*c_E;
    
 
 w__E_ded_to_de_de=3.3241E-8*c_E;
  w__E_ded_to_de_de__by_de=1.6064E-5*c_E;
  w__E_ded_to_de_de__by_ded=2.2436E-5*c_E;
  w__E_ded_to_de_de__by_e=0.19988*c_E;
 
    w__d_de_to_ded=4.7654E-5;
    w__d_e_to_de=0.54231;
    w__d_to_D__s=0.315;  % (Nonlinear remove from expermental, "Loose 2011, most notably") 
    w__de_de_to_ded_E=0;
    w__de_de_to_ded_e=0.00059851;
    w__de_to_D_E=0.19633;
    w__de_to_D_e=7.4886E-7;
    w__de_to_d_E=0;
    
    w__de_to_d_e=0.053617; %%Not INCLUDED.
    
    w__ded_e_to_de_de=9.7325;
    
    w__ded_to_D_E_D=0;
    w__ded_to_D_E_d=0;
    w__ded_to_D_de=0;
    w__ded_to_D_e_D=0;
    w__ded_to_D_e_d=0;
    w__ded_to_d_de=7.1814*10^-6;
    w__e_to_E=0.051613;
    %Parameters loaded in.

    
    
c_d_prime=(...
     w__D_to_d.*(d_max-d_b-c_d-c_de-2.*c_ded)./d_max ...
    +w__D_to_d__by_d.*(d_max-d_b-c_d-c_de-2.*c_ded)./d_max.*c_d ...
    +w__D_to_d__by_de.*(d_max-d_b-c_d-c_de-2.*c_ded)./d_max.*c_de ...
    +w__D_to_d__by_ded.*(d_max-d_b-c_d-c_de-2.*c_ded)./d_max.*c_ded ...
    ...
    -w__E_d_to_de.*c_d ...
    -w__E_d_to_de__by_de.*c_d.*c_de ...
    -w__E_d_to_de__by_ded.*c_d.*c_ded ...
    -w__E_d_to_de__by_e.*c_d.*c_e ...
    ...
    -w__d_to_D__s.*d_s.^n_s./(d_s.^n_s+(d_b+c_d+c_de+2.*c_ded).^n_s).*c_d ...
    -w__d_de_to_ded.*c_d.*c_de ...
    -w__d_e_to_de.*c_d.*c_e ...
    ...
    +w__de_to_d_E.*c_de ...
    +w__de_to_d_e.*c_de ...    
    ...
    +w__ded_to_D_E_d.*c_ded ...
    +w__ded_to_D_e_d.*c_ded ...
    +w__ded_to_d_de.*c_ded ...
            ).*(data_track_identity>=0);

c_de_prime=(...
     w__E_d_to_de.*c_d ...
    +w__E_d_to_de__by_de.*c_d.*c_de ...
    +w__E_d_to_de__by_ded.*c_d.*c_ded ...
    +w__E_d_to_de__by_e.*c_d.*c_e ...
  +2*w__E_ded_to_de_de.*c_ded ...
  +2*w__E_ded_to_de_de__by_de.*c_ded.*c_de ...
  +2*w__E_ded_to_de_de__by_ded.*c_ded.*c_ded ...
  +2*w__E_ded_to_de_de__by_e.*c_ded.*c_e ...
     ...
    -w__d_de_to_ded.*c_d.*c_de ...
    +w__d_e_to_de.*c_d.*c_e ...
    ...
    -2*w__de_de_to_ded_E.*c_de.^2 ...
    -2*w__de_de_to_ded_e.*c_de.^2 ...
    -w__de_to_D_E.*c_de ...
    -w__de_to_D_e.*c_de ...
    -w__de_to_d_E.*c_de ...
    -w__de_to_d_e.*c_de ...
    ...
    +w__ded_to_D_de.*c_ded ...
    +w__ded_to_d_de.*c_ded ...
  +2*w__ded_e_to_de_de.*c_ded.*c_e ...
             ).*(data_track_identity>=0);

c_ded_prime=(...
   -w__E_ded_to_de_de.*c_ded ...
   -w__E_ded_to_de_de__by_de.*c_ded.*c_de ...
   -w__E_ded_to_de_de__by_ded.*c_ded.*c_ded ...
   -w__E_ded_to_de_de__by_e.*c_ded.*c_e ...
    ...
   +w__d_de_to_ded.*c_d.*c_de ...
    ...
   +w__de_de_to_ded_E.*c_de.^2 ...
   +w__de_de_to_ded_e.*c_de.^2 ...
    ...
   -w__ded_to_D_E_D.*c_ded ...
   -w__ded_to_D_E_d.*c_ded ...
   -w__ded_to_D_de.*c_ded ...
   -w__ded_to_D_e_D.*c_ded ...
   -w__ded_to_D_e_d.*c_ded ...
   -w__ded_to_d_de.*c_ded ...
   -w__ded_e_to_de_de.*c_ded.*c_e ...
              ).*(data_track_identity>=0);

c_e_prime=(...
  -w__d_e_to_de.*c_d.*c_e ...
  ...
  +w__de_de_to_ded_e.*c_de.^2 ...
  +w__de_to_D_e.*c_de ...
  +w__de_to_d_e.*c_de ...
  ...
  +w__ded_to_D_e_D.*c_ded ...
  +w__ded_to_D_e_d.*c_ded ...
  -w__ded_e_to_de_de.*c_ded.*c_e ...
  ...
  -w__e_to_E.*c_e ...
            ).*(data_track_identity>=0);
        
        
y=[c_d_prime;c_de_prime;c_ded_prime;c_e_prime];

end
